Null-safety migration
meilisearch/meilisearch-dart pull request #42
Opened 2021-05-03 19:18 UTC by TheMisir

Fixes #37

2021-05-03 19:23 UTC, TheMisir commented
Actually I think nnbd version should be maintained separately on different branch for some time. At least that's what we did when migrating [hive](https://github.com/hivedb/hive) to nnbd.

2021-05-05 07:25 UTC, curquiza commented
Hello @TheMisir! Thanks for doing this work :)
Ping me when you have finished this PR 🙂

2021-05-05 09:30 UTC, TheMisir commented
@curquiza it's ready. Just updated `pubspec.yaml` version to v0.2.0 and tests are passing (if dart >2.12).

2021-05-05 16:49 UTC, curquiza requested changes
Thanks a lot @TheMisir 😄

- Can you update the [bors.toml](https://github.com/meilisearch/meilisearch-dart/blob/main/bors.toml) file please? Some tests have to be removed 😇
- Does the README need changes? I think about the `Getting Started` section

2021-05-05 16:51 UTC, curquiza requested changes

2021-05-05 16:51 UTC, curquiza commented on .github/workflows/tests.yml
> +      - nnbd
```suggestion
```

2021-05-05 16:52 UTC, TheMisir commented
> * Can you update the [bors.toml](https://github.com/meilisearch/meilisearch-dart/blob/main/bors.toml) file please? Some tests have to be removed 😇

I've updated `bors.toml` because testing requires dart ^2.12.

2021-05-05 16:57 UTC, curquiza commented
> I've updated bors.toml because testing null safety requires dart ^2.12.

My bad, I miss checked! :)

2021-05-06 18:06 UTC, curquiza approved these changes
Awesome!! 🔥 Thanks @TheMisir!

2021-05-06 18:06 UTC, curquiza commented
bors merge

2021-05-06 18:07 UTC, merged

2021-05-06 18:15 UTC, TheMisir commented
@curquiza out of context, but what does **bors** exactly?

2021-05-06 18:22 UTC, curquiza commented
TLDR: Bors is a tool that applies a rebase before running the tests and finally merging if they succeed.

To be more accurate, Bors does not concretely rebase the branch of the PR: it merges the commits of the PR into another branch (staging) that is already up-to-date with main. If the tests do not pass on the staging branch, Bors returns a failure and stops the merge of the PR.

We use it because:
- we don't have to ask the contributors to rebase anymore which is a really nice point 😁
- it can handle multiple PRs at the same time: no need to wait for the PR of your colleague to be merged to merge yours.

I wrote a guide about it here: https://github.com/meilisearch/integration-guides/blob/main/guides/bors.md
Also, I wrote an article about our usage of bors, but it's not released yet 😇 

Also, bors is a tool widely used (and created) by the rust community

2021-05-06 18:36 UTC, TheMisir commented
Thanks 🙏